run:
  speculos target/flex/release/app-vanadium

run-nanox:
  speculos target/nanox/release/app-vanadium

run-nanosplus:
  speculos target/nanosplus/release/app-vanadium

run-flex:
  speculos target/flex/release/app-vanadium

run-stax:
  speculos target/stax/release/app-vanadium

run-apex_p:
  speculos target/apex_p/release/app-vanadium


# note: the load-* commands only work after compiling with the VSCode extension

load-nanosplus:
  python3 -m ledgerblue.runScript  --scp --fileName build/nanos2/bin/app.apdu --elfFile build/nanos2/bin/app.elf

load-nanox:
  python3 -m ledgerblue.runScript  --scp --fileName build/nanox/bin/app.apdu --elfFile build/nanox/bin/app.elf
  
load-flex:
  python3 -m ledgerblue.runScript  --scp --fileName build/flex/bin/app.apdu --elfFile build/flex/bin/app.elf

load-stax:
  python3 -m ledgerblue.runScript  --scp --fileName build/stax/bin/app.apdu --elfFile build/stax/bin/app.elf

load-apex_p:
  python3 -m ledgerblue.runScript  --scp --fileName build/apex_p/bin/app.apdu --elfFile build/apex_p/bin/app.elf

