run:
  cargo run

# build for both native and riscv targets
build:
  cargo build --release --target=x86_64-unknown-linux-gnu
  cargo build --release --target=riscv32imc-unknown-none-elf

# build for native target
build-native:
  cargo build --release --target=x86_64-unknown-linux-gnu

# build for riscv target
build-riscv:
  cargo build --release --target=riscv32imc-unknown-none-elf

# disassembles the riscv binary
disassemble:
  riscv64-linux-gnu-objdump -d target/riscv32imc-unknown-none-elf/release/vnd-test

# show the sections of the riscv binary
show-sections:
  readelf -S target/riscv32imc-unknown-none-elf/release/vnd-test
