
# build for both native and riscv targets
build:
  cargo build --release
  cargo build --release --target=riscv32imc-unknown-none-elf

# build for native target
build-native:
  cargo build --release

# build for riscv target
build-riscv:
  cargo build --release --target=riscv32imc-unknown-none-elf

